server:
  port: 28081

spring:
  application:
    name: rocketmq-produce-example-wucfu
  cloud:
    stream:
      bindings:
        output1:
          destination: test-topic
          content-type: application/json
        output2:
          destination: TransactionTopic
          content-type: application/json
        output3:
          destination: pull-topic
          content-type: text/plain
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
        bindings:
          output1:
            producer:
              group: binder-group
              sync: true
          output2:
            producer:
              group: myTxProducerGroup
              transactional: true
          output3:
            producer:
              group: pull-binder-group
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
logging:
  level:
    com:
      alibaba:
        cloud:
          stream:
            binder:
              rocketmq: DEBUG