server:
  port: 8687

spring:
  application:
    name: service-provider-wucfu
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'
